@startuml

skinparam rectangle {
    BackgroundColor E8E8E8
    FontColor Black
    FontSize 25
    
    BackgroundColor<<Area Energy System>> faa634

    BackgroundColor<<House Energy System [1..n]>> 76c58c

    BackgroundColor<<House Heating System>> 61c2ee
    BackgroundColor<<House Electrical System>> 61c2ee

    BackgroundColor<<House Domestic Hot Water System>> fde051
    BackgroundColor<<House Heat Production System>> fde051
    BackgroundColor<<House Heat Delivery System>> fde051
    BackgroundColor<<House Electricity Production System>> fde051
    
    BackgroundColor<<House Heat Delivery Group [1..n]>> f04e37
    BackgroundColor<<House Heat Delivery Element [1..n]>> b43e97
}

rectangle "OPEN SOURCE ENERGY MANAGER SYSTEM LAYERS" {
    rectangle <<Area Energy System>> {
        rectangle <<House Energy System [1..n]>> {
            rectangle <<House Electrical System>> {
                rectangle <<House Electricity Production System>> {
                }
            }
            rectangle <<House Heating System>> {
                rectangle <<House Heat Production System>> {
                }
                rectangle <<House Heat Delivery System>> {
                    rectangle <<House Heat Delivery Group [1..n]>> {
                        rectangle <<House Heat Delivery Element [1..n]>> {
                        }
                    }
                }
                rectangle <<House Domestic Hot Water System>> {
                }
            }
        }
    }
}

@enduml
